name: clinic_management
description: A clinic management system with Flutter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # API & Network
  http: ^1.1.0
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Routing
  go_router: ^16.3.0
  
  # Date & Time
  intl: ^0.20.2

  
  # Forms & Validation
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  
  # Charts & Reports
  fl_chart: ^1.1.1
  syncfusion_flutter_charts: ^31.2.3
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Image Picker
  image_picker: ^1.0.7
  
  # Loading & Dialogs
  flutter_spinkit: ^5.2.0
  awesome_dialog: ^3.2.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.5.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/
  #   - assets/icons/